using System.ComponentModel.DataAnnotations;

namespace HomeFixService.WebService.Models.Enums
{
    public enum Currency
    {
        [Display(Name = "AFN", Description = "Afghan afghani")] AFN,
        [Display(Name = "EUR", Description = "European euro")] EUR,
        [Display(Name = "ALL", Description = "Albanian lek")] ALL,
        [Display(Name = "DZD", Description = "Algerian dinar")] DZD,
        [Display(Name = "AOA", Description = "Angolan kwanza")] AOA,
        [Display(Name = "ARS", Description = "Argentine peso")] ARS,
        [Display(Name = "AMD", Description = "Armenian dram")] AMD,
        [Display(Name = "AWG", Description = "Aruban florin")] AWG,
        [Display(Name = "AZN", Description = "Azerbaijani manat")] AZN,
        [Display(Name = "BSD", Description = "Bahamian dollar")] BSD,
        [Display(Name = "BHD", Description = "Bahraini dinar")] BHD,
        [Display(Name = "BDT", Description = "Bangladeshi taka")] BDT,
        [Display(Name = "BBD", Description = "Barbadian dollar")] BBD,
        [Display(Name = "BYN", Description = "Belarusian ruble")] BYN,
        [Display(Name = "BZD", Description = "Belize dollar")] BZD,
        [Display(Name = "BMD", Description = "Bermudian dollar")] BMD,
        [Display(Name = "BTN", Description = "Bhutanese ngultrum")] BTN,
        [Display(Name = "BOB", Description = "Bolivian boliviano")] BOB,
        [Display(Name = "BAM", Description = "Bosnia and Herzegovina convertible mark")] BAM,
        [Display(Name = "BWP", Description = "Botswana pula")] BWP,
        [Display(Name = "BRL", Description = "Brazilian real")] BRL,
        [Display(Name = "BND", Description = "Brunei dollar")] BND,
        [Display(Name = "BGN", Description = "Bulgarian lev")] BGN,
        [Display(Name = "BIF", Description = "Burundi franc")] BIF,
        [Display(Name = "CVE", Description = "Cape Verdean escudo")] CVE,
        [Display(Name = "KHR", Description = "Cambodian riel")] KHR,
        [Display(Name = "CAD", Description = "Canadian dollar")] CAD,
        [Display(Name = "KYD", Description = "Cayman Islands dollar")] KYD,
        [Display(Name = "CLP", Description = "Chilean peso")] CLP,
        [Display(Name = "CNY", Description = "Chinese Yuan Renminbi")] CNY,
        [Display(Name = "COP", Description = "Colombian peso")] COP,
        [Display(Name = "KMF", Description = "Comorian franc")] KMF,
        [Display(Name = "CDF", Description = "Congolese franc")] CDF,
        [Display(Name = "CRC", Description = "Costa Rican colon")] CRC,
        [Display(Name = "HRK", Description = "Croatian kuna")] HRK,
        [Display(Name = "CUP", Description = "Cuban peso")] CUP,
        [Display(Name = "CZK", Description = "Czech koruna")] CZK,
        [Display(Name = "DJF", Description = "Djiboutian franc")] DJF,
        [Display(Name = "DOP", Description = "Dominican peso")] DOP,
        [Display(Name = "EGP", Description = "Egyptian pound")] EGP,
        [Display(Name = "ERN", Description = "Eritrean nakfa")] ERN,
        [Display(Name = "ETB", Description = "Ethiopian birr")] ETB,
        [Display(Name = "FKP", Description = "Falkland Islands pound")] FKP,
        [Display(Name = "FJD", Description = "Fijian dollar")] FJD,
        [Display(Name = "XAF", Description = "Central African CFA franc")] XAF,
        [Display(Name = "GMD", Description = "Gambian dalasi")] GMD,
        [Display(Name = "GEL", Description = "Georgian lari")] GEL,
        [Display(Name = "GHS", Description = "Ghanaian cedi")] GHS,
        [Display(Name = "GIP", Description = "Gibraltar pound")] GIP,
        [Display(Name = "DKK", Description = "Danish krone")] DKK,
        [Display(Name = "GTQ", Description = "Guatemalan quetzal")] GTQ,
        [Display(Name = "GGP", Description = "Guernsey Pound")] GGP,
        [Display(Name = "GNF", Description = "Guinean franc")] GNF,
        [Display(Name = "GYD", Description = "Guyanese dollar")] GYD,
        [Display(Name = "HTG", Description = "Haitian gourde")] HTG,
        [Display(Name = "HNL", Description = "Honduran lempira")] HNL,
        [Display(Name = "HKD", Description = "Hong Kong dollar")] HKD,
        [Display(Name = "HUF", Description = "Hungarian forint")] HUF,
        [Display(Name = "ISK", Description = "Icelandic krona")] ISK,
        [Display(Name = "INR", Description = "Indian rupee")] INR,
        [Display(Name = "IDR", Description = "Indonesian rupiah")] IDR,
        [Display(Name = "XDR", Description = "SDR (Special Drawing Right)")] XDR,
        [Display(Name = "IRR", Description = "Iranian rial")] IRR,
        [Display(Name = "IQD", Description = "Iraqi dinar")] IQD,
        [Display(Name = "IMP", Description = "Manx pound")] IMP,
        [Display(Name = "JMD", Description = "Jamaican dollar")] JMD,
        [Display(Name = "JPY", Description = "Japanese yen")] JPY,
        [Display(Name = "JEP", Description = "Jersey pound")] JEP,
        [Display(Name = "JOD", Description = "Jordanian dinar")] JOD,
        [Display(Name = "KZT", Description = "Kazakhstani tenge")] KZT,
        [Display(Name = "KES", Description = "Kenyan shilling")] KES,
        [Display(Name = "KWD", Description = "Kuwaiti dinar")] KWD,
        [Display(Name = "KGS", Description = "Kyrgyzstani som")] KGS,
        [Display(Name = "LAK", Description = "Lao kip")] LAK,
        [Display(Name = "LBP", Description = "Lebanese pound")] LBP,
        [Display(Name = "LSL", Description = "Lesotho loti")] LSL,
        [Display(Name = "LRD", Description = "Liberian dollar")] LRD,
        [Display(Name = "LYD", Description = "Libyan dinar")] LYD,
        [Display(Name = "MOP", Description = "Macanese pataca")] MOP,
        [Display(Name = "MKD", Description = "Macedonian denar")] MKD,
        [Display(Name = "MGA", Description = "Malagasy ariary")] MGA,
        [Display(Name = "MWK", Description = "Malawian kwacha")] MWK,
        [Display(Name = "MYR", Description = "Malaysian ringgit")] MYR,
        [Display(Name = "MVR", Description = "Maldivian rufiyaa")] MVR,
        [Display(Name = "MRO", Description = "Mauritanian ouguiya")] MRO,
        [Display(Name = "MUR", Description = "Mauritian rupee")] MUR,
        [Display(Name = "MXN", Description = "Mexican peso")] MXN,
        [Display(Name = "MDL", Description = "Moldovan leu")] MDL,
        [Display(Name = "MNT", Description = "Mongolian tugrik")] MNT,
        [Display(Name = "MAD", Description = "Moroccan dirham")] MAD,
        [Display(Name = "MZN", Description = "Mozambican metical")] MZN,
        [Display(Name = "MMK", Description = "Myanmar kyat")] MMK,
        [Display(Name = "NAD", Description = "Namibian dollar")] NAD,
        [Display(Name = "NPR", Description = "Nepalese rupee")] NPR,
        [Display(Name = "NIO", Description = "Nicaraguan cordoba")] NIO,
        [Display(Name = "NGN", Description = "Nigerian naira")] NGN,
        [Display(Name = "KPW", Description = "North Korean won")] KPW,
        [Display(Name = "OMR", Description = "Omani rial")] OMR,
        [Display(Name = "PKR", Description = "Pakistani rupee")] PKR,
        [Display(Name = "ILS", Description = "Israeli new shekel")] ILS,
        [Display(Name = "PGK", Description = "Papua New Guinean kina")] PGK,
        [Display(Name = "PYG", Description = "Paraguayan guarani")] PYG,
        [Display(Name = "PEN", Description = "Peruvian sol")] PEN,
        [Display(Name = "PHP", Description = "Philippine peso")] PHP,
        [Display(Name = "PLN", Description = "Polish zloty")] PLN,
        [Display(Name = "QAR", Description = "Qatari riyal")] QAR,
        [Display(Name = "RON", Description = "Romanian leu")] RON,
        [Display(Name = "RUB", Description = "Russian ruble")] RUB,
        [Display(Name = "RWF", Description = "Rwandan franc")] RWF,
        [Display(Name = "SHP", Description = "Saint Helena pound")] SHP,
        [Display(Name = "WST", Description = "Samoan tala")] WST,
        [Display(Name = "STD", Description = "Sao Tome and Principe dobra")] STD,
        [Display(Name = "SAR", Description = "Saudi Arabian riyal")] SAR,
        [Display(Name = "RSD", Description = "Serbian dinar")] RSD,
        [Display(Name = "SCR", Description = "Seychellois rupee")] SCR,
        [Display(Name = "SLL", Description = "Sierra Leonean leone")] SLL,
        [Display(Name = "SGD", Description = "Singapore dollar")] SGD,
        [Display(Name = "ANG", Description = "Netherlands Antillean guilder")] ANG,
        [Display(Name = "SBD", Description = "Solomon Islands dollar")] SBD,
        [Display(Name = "SOS", Description = "Somali shilling")] SOS,
        [Display(Name = "ZAR", Description = "South African rand")] ZAR,
        [Display(Name = "KRW", Description = "South Korean won")] KRW,
        [Display(Name = "SSP", Description = "South Sudanese pound")] SSP,
        [Display(Name = "LKR", Description = "Sri Lankan rupee")] LKR,
        [Display(Name = "SDG", Description = "Sudanese pound")] SDG,
        [Display(Name = "SRD", Description = "Surinamese dollar")] SRD,
        [Display(Name = "NOK", Description = "Norwegian krone")] NOK,
        [Display(Name = "SZL", Description = "Swazi lilangeni")] SZL,
        [Display(Name = "SEK", Description = "Swedish krona")] SEK,
        [Display(Name = "CHF", Description = "Swiss franc")] CHF,
        [Display(Name = "SYP", Description = "Syrian pound")] SYP,
        [Display(Name = "TWD", Description = "New Taiwan dollar")] TWD,
        [Display(Name = "TJS", Description = "Tajikistani somoni")] TJS,
        [Display(Name = "TZS", Description = "Tanzanian shilling")] TZS,
        [Display(Name = "THB", Description = "Thai baht")] THB,
        [Display(Name = "XOF", Description = "West African CFA franc")] XOF,
        [Display(Name = "NZD", Description = "New Zealand dollar")] NZD,
        [Display(Name = "TOP", Description = "Tongan pa’anga")] TOP,
        [Display(Name = "TTD", Description = "Trinidad and Tobago dollar")] TTD,
        [Display(Name = "TND", Description = "Tunisian dinar")] TND,
        [Display(Name = "TRY", Description = "Turkish lira")] TRY,
        [Display(Name = "TMT", Description = "Turkmen manat")] TMT,
        [Display(Name = "AUD", Description = "Australian dollar")] AUD,
        [Display(Name = "UGX", Description = "Ugandan shilling")] UGX,
        [Display(Name = "UAH", Description = "Ukrainian hryvnia")] UAH,
        [Display(Name = "AED", Description = "UAE dirham")] AED,
        [Display(Name = "GBP", Description = "Pound sterling")] GBP,
        [Display(Name = "UYU", Description = "Uruguayan peso")] UYU,
        [Display(Name = "UZS", Description = "Uzbekistani som")] UZS,
        [Display(Name = "VUV", Description = "Vanuatu vatu")] VUV,
        [Display(Name = "VEF", Description = "Venezuelan bolivar")] VEF,
        [Display(Name = "VND", Description = "Vietnamese dong")] VND,
        [Display(Name = "XPF", Description = "CFP franc")] XPF,
        [Display(Name = "YER", Description = "Yemeni rial")] YER,
        [Display(Name = "ZMW", Description = "Zambian kwacha")] ZMW,
        [Display(Name = "Cook Islands dollar", Description = "Cook Islands dollar")] COOK_INSLAND_DOLLAR,
        [Display(Name = "Faroese krona", Description = "Faroese krona")] FAROESE_KRONA
    }
}