using System.ComponentModel;

namespace HomeFixService.WebService.Models.Enums
{
    public enum CurrencyEnum
    {
        [Description("Afghan afghani")] AFN = 1,
        [Description("European euro")] EUR,
        [Description("Albanian lek")] ALL,
        [Description("Algerian dinar")] DZD,
        [Description("Angolan kwanza")] AOA,
        [Description("Argentine peso")] ARS,
        [Description("Armenian dram")] AMD,
        [Description("Aruban florin")] AWG,
        [Description("Azerbaijani manat")] AZN,
        [Description("Bahamian dollar")] BSD,
        [Description("Bahraini dinar")] BHD,
        [Description("Bangladeshi taka")] BDT,
        [Description("Barbadian dollar")] BBD,
        [Description("Belarusian ruble")] BYN,
        [Description("Belize dollar")] BZD,
        [Description("Bermudian dollar")] BMD,
        [Description("Bhutanese ngultrum")] BTN,
        [Description("Bolivian boliviano")] BOB,
        [Description("Bosnia and Herzegovina convertible mark")] BAM,
        [Description("Botswana pula")] BWP,
        [Description("Brazilian real")] BRL,
        [Description("Brunei dollar")] BND,
        [Description("Bulgarian lev")] BGN,
        [Description("Burundi franc")] BIF,
        [Description("Cape Verdean escudo")] CVE,
        [Description("Cambodian riel")] KHR,
        [Description("Canadian dollar")] CAD,
        [Description("Cayman Islands dollar")] KYD,
        [Description("Chilean peso")] CLP,
        [Description("Chinese Yuan Renminbi")] CNY,
        [Description("Colombian peso")] COP,
        [Description("Comorian franc")] KMF,
        [Description("Congolese franc")] CDF,
        [Description("Costa Rican colon")] CRC,
        [Description("Croatian kuna")] HRK,
        [Description("Cuban peso")] CUP,
        [Description("Czech koruna")] CZK,
        [Description("Djiboutian franc")] DJF,
        [Description("Dominican peso")] DOP,
        [Description("Egyptian pound")] EGP,
        [Description("Eritrean nakfa")] ERN,
        [Description("Ethiopian birr")] ETB,
        [Description("Falkland Islands pound")] FKP,
        [Description("Fijian dollar")] FJD,
        [Description("Central African CFA franc")] XAF,
        [Description("Gambian dalasi")] GMD,
        [Description("Georgian lari")] GEL,
        [Description("Ghanaian cedi")] GHS,
        [Description("Gibraltar pound")] GIP,
        [Description("Danish krone")] DKK,
        [Description("Guatemalan quetzal")] GTQ,
        [Description("Guernsey Pound")] GGP,
        [Description("Guinean franc")] GNF,
        [Description("Guyanese dollar")] GYD,
        [Description("Haitian gourde")] HTG,
        [Description("Honduran lempira")] HNL,
        [Description("Hong Kong dollar")] HKD,
        [Description("Hungarian forint")] HUF,
        [Description("Icelandic krona")] ISK,
        [Description("Indian rupee")] INR,
        [Description("Indonesian rupiah")] IDR,
        [Description("SDR (Special Drawing Right)")] XDR,
        [Description("Iranian rial")] IRR,
        [Description("Iraqi dinar")] IQD,
        [Description("Manx pound")] IMP,
        [Description("Jamaican dollar")] JMD,
        [Description("Japanese yen")] JPY,
        [Description("Jersey pound")] JEP,
        [Description("Jordanian dinar")] JOD,
        [Description("Kazakhstani tenge")] KZT,
        [Description("Kenyan shilling")] KES,
        [Description("Kuwaiti dinar")] KWD,
        [Description("Kyrgyzstani som")] KGS,
        [Description("Lao kip")] LAK,
        [Description("Lebanese pound")] LBP,
        [Description("Lesotho loti")] LSL,
        [Description("Liberian dollar")] LRD,
        [Description("Libyan dinar")] LYD,
        [Description("Macanese pataca")] MOP,
        [Description("Macedonian denar")] MKD,
        [Description("Malagasy ariary")] MGA,
        [Description("Malawian kwacha")] MWK,
        [Description("Malaysian ringgit")] MYR,
        [Description("Maldivian rufiyaa")] MVR,
        [Description("Mauritanian ouguiya")] MRO,
        [Description("Mauritian rupee")] MUR,
        [Description("Mexican peso")] MXN,
        [Description("Moldovan leu")] MDL,
        [Description("Mongolian tugrik")] MNT,
        [Description("Moroccan dirham")] MAD,
        [Description("Mozambican metical")] MZN,
        [Description("Myanmar kyat")] MMK,
        [Description("Namibian dollar")] NAD,
        [Description("Nepalese rupee")] NPR,
        [Description("Nicaraguan cordoba")] NIO,
        [Description("Nigerian naira")] NGN,
        [Description("North Korean won")] KPW,
        [Description("Omani rial")] OMR,
        [Description("Pakistani rupee")] PKR,
        [Description("Israeli new shekel")] ILS,
        [Description("Papua New Guinean kina")] PGK,
        [Description("Paraguayan guarani")] PYG,
        [Description("Peruvian sol")] PEN,
        [Description("Philippine peso")] PHP,
        [Description("Polish zloty")] PLN,
        [Description("Qatari riyal")] QAR,
        [Description("Romanian leu")] RON,
        [Description("Russian ruble")] RUB,
        [Description("Rwandan franc")] RWF,
        [Description("Saint Helena pound")] SHP,
        [Description("Samoan tala")] WST,
        [Description("Sao Tome and Principe dobra")] STD,
        [Description("Saudi Arabian riyal")] SAR,
        [Description("Serbian dinar")] RSD,
        [Description("Seychellois rupee")] SCR,
        [Description("Sierra Leonean leone")] SLL,
        [Description("Singapore dollar")] SGD,
        [Description("Netherlands Antillean guilder")] ANG,
        [Description("Solomon Islands dollar")] SBD,
        [Description("Somali shilling")] SOS,
        [Description("South African rand")] ZAR,
        [Description("South Korean won")] KRW,
        [Description("South Sudanese pound")] SSP,
        [Description("Sri Lankan rupee")] LKR,
        [Description("Sudanese pound")] SDG,
        [Description("Surinamese dollar")] SRD,
        [Description("Norwegian krone")] NOK,
        [Description("Swazi lilangeni")] SZL,
        [Description("Swedish krona")] SEK,
        [Description("Swiss franc")] CHF,
        [Description("Syrian pound")] SYP,
        [Description("New Taiwan dollar")] TWD,
        [Description("Tajikistani somoni")] TJS,
        [Description("Tanzanian shilling")] TZS,
        [Description("Thai baht")] THB,
        [Description("West African CFA franc")] XOF,
        [Description("New Zealand dollar")] NZD,
        [Description("Tongan pa’anga")] TOP,
        [Description("Trinidad and Tobago dollar")] TTD,
        [Description("Tunisian dinar")] TND,
        [Description("Turkish lira")] TRY,
        [Description("Turkmen manat")] TMT,
        [Description("Australian dollar")] AUD,
        [Description("Ugandan shilling")] UGX,
        [Description("Ukrainian hryvnia")] UAH,
        [Description("UAE dirham")] AED,
        [Description("Pound sterling")] GBP,
        [Description("Uruguayan peso")] UYU,
        [Description("Uzbekistani som")] UZS,
        [Description("Vanuatu vatu")] VUV,
        [Description("Venezuelan bolivar")] VEF,
        [Description("Vietnamese dong")] VND,
        [Description("CFP franc")] XPF,
        [Description("Yemeni rial")] YER,
        [Description("Zambian kwacha")] ZMW,
        [Description("Cook Islands dollar")] COOK_INSLAND_DOLLAR,
        [Description("Faroese krona")] FAROESE_KRONA
    }
}